// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6m6SWvyFzc5E5Wg2o_xBzVKmEu2TzCd4',
    appId: '1:1061819191154:web:1c5790809d6e00514957eb',
    messagingSenderId: '1061819191154',
    projectId: 'beauty-salon-app-15368',
    authDomain: 'beauty-salon-app-15368.firebaseapp.com',
    storageBucket: 'beauty-salon-app-15368.firebasestorage.app',
    measurementId: 'G-KNQ751ENN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMhsNy2-LF_46ACaWuHMBGv7AlkhOrciY',
    appId: '1:1061819191154:android:41026f38cb7e93904957eb',
    messagingSenderId: '1061819191154',
    projectId: 'beauty-salon-app-15368',
    storageBucket: 'beauty-salon-app-15368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPIiAPrOLsljrDCR93Anwqgv7v3FYgVmU',
    appId: '1:1061819191154:ios:c7c2304815bbb6bb4957eb',
    messagingSenderId: '1061819191154',
    projectId: 'beauty-salon-app-15368',
    storageBucket: 'beauty-salon-app-15368.firebasestorage.app',
    iosBundleId: 'com.example.beautySalonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPIiAPrOLsljrDCR93Anwqgv7v3FYgVmU',
    appId: '1:1061819191154:ios:c7c2304815bbb6bb4957eb',
    messagingSenderId: '1061819191154',
    projectId: 'beauty-salon-app-15368',
    storageBucket: 'beauty-salon-app-15368.firebasestorage.app',
    iosBundleId: 'com.example.beautySalonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6m6SWvyFzc5E5Wg2o_xBzVKmEu2TzCd4',
    appId: '1:1061819191154:web:52efb5bfe061079b4957eb',
    messagingSenderId: '1061819191154',
    projectId: 'beauty-salon-app-15368',
    authDomain: 'beauty-salon-app-15368.firebaseapp.com',
    storageBucket: 'beauty-salon-app-15368.firebasestorage.app',
    measurementId: 'G-BPJKQKMY1Q',
  );
}
